version: '3.8'
services:
  flask-app:
    networks:
      - staging-network

  node-addin:
    networks:
      - staging-network

networks:
  staging-network:
    external: true
    name: staging-network  # Explicitly set the network name
