version: '3.8'
services:
  flask-app:
    networks:
      - production-network

  node-addin:
    networks:
      - production-network

networks:
  production-network:
    name: production-network  # Explicitly set the network name
