version: '3.8'
services:
  flask-app:
    container_name: ${FLASK_ENV:-dev}_flask_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${FLASK_HOST_PORT:-5000}:5000"
    env_file:
      - .env.${FLASK_ENV:-dev}
    environment:
      - FLASK_ENV=${FLASK_ENV:-dev}
    volumes:
      - .:/app
    depends_on:
      - node-addin
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "db-host:172.21.0.1"
    networks:
      app-network:
        ipv4_address: 172.21.0.3

  node-addin:
    container_name: ${FLASK_ENV:-dev}_node_addin
    build: ./excel_addin
    ports:
      - "${NODE_HOST_PORT:-3000}:3000"
    volumes:
      - ./excel_addin:/app
    networks:
      app-network:
        ipv4_address: 172.21.0.4

networks:
  app-network:
    name: ${FLASK_ENV:-dev}_app_net
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/24
    driver_opts:
      com.docker.network.bridge.name: app-net-${FLASK_ENV:-dev}
