version: '3.8'
services:
  flask-app:
    networks:
      default:
        ipv4_address: 172.20.0.3

  node-addin:
    networks:
      default:
        ipv4_address: 172.20.0.4

networks:
  default:
    ipam:
      config:
        - subnet: 172.20.0.0/16
    driver_opts:
      com.docker.network.bridge.name: vps-local-stag