version: '3.8'
services:
  flask-app:
    networks:
      staging-network:
        ipv4_address: 172.30.0.3

  node-addin:
    networks:
      staging-network:
        ipv4_address: 172.30.0.4

networks:
  staging-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16