"""Updated PlaidTransaction model

Revision ID: 132b2dc80e84
Revises: 972b0e8b1cb3
Create Date: 2023-11-28 20:08:23.058925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '132b2dc80e84'
down_revision = '972b0e8b1cb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plaid_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('posted_transactions', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pending_transactions', sa.Integer(), nullable=True))
        batch_op.drop_column('balance')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plaid_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance', sa.FLOAT(), nullable=True))
        batch_op.drop_column('pending_transactions')
        batch_op.drop_column('posted_transactions')

    # ### end Alembic commands ###
