"""Remove username field from User model

Revision ID: 1458f4e38d80
Revises: fbae095257ee
Create Date: 2025-02-19 17:37:21.618272

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1458f4e38d80'
down_revision = 'fbae095257ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('username')
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', mysql.VARCHAR(length=80), nullable=False))
        batch_op.create_index('username', ['username'], unique=True)

    # ### end Alembic commands ###
