"""empty message

Revision ID: 15969fc642c3
Revises: 6a0537905d47
Create Date: 2025-10-16 21:49:53.846410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15969fc642c3'
down_revision = '6a0537905d47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_category_override', schema=None) as batch_op:
        batch_op.drop_constraint('transaction_category_override_ibfk_1', type_='foreignkey')

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_new', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('seen_by_user', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('last_seen_by_user', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('last_seen_by_user')
        batch_op.drop_column('seen_by_user')
        batch_op.drop_column('is_new')

    with op.batch_alter_table('transaction_category_override', schema=None) as batch_op:
        batch_op.create_foreign_key('transaction_category_override_ibfk_1', 'transactions', ['transaction_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
