"""empty message

Revision ID: 15969fc642c3
Revises: 6a0537905d47
Create Date: 2025-10-16 21:49:53.846410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15969fc642c3'
down_revision = '6a0537905d47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    fk_constraints = inspector.get_foreign_keys('transaction_category_override')
    fk_names = {fk['name'] for fk in fk_constraints if fk.get('name')}

    if 'transaction_category_override_ibfk_1' in fk_names:
        with op.batch_alter_table('transaction_category_override', schema=None) as batch_op:
            batch_op.drop_constraint('transaction_category_override_ibfk_1', type_='foreignkey')

    transaction_columns = {column['name'] for column in inspector.get_columns('transactions')}

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        if 'is_new' not in transaction_columns:
            batch_op.add_column(sa.Column('is_new', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        if 'seen_by_user' not in transaction_columns:
            batch_op.add_column(sa.Column('seen_by_user', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        if 'last_seen_by_user' not in transaction_columns:
            batch_op.add_column(sa.Column('last_seen_by_user', sa.DateTime(), nullable=True))

    # remove server defaults that were added to allow non-null insert
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        if 'is_new' not in transaction_columns:
            batch_op.alter_column('is_new', server_default=None)
        if 'seen_by_user' not in transaction_columns:
            batch_op.alter_column('seen_by_user', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('last_seen_by_user')
        batch_op.drop_column('seen_by_user')
        batch_op.drop_column('is_new')

    with op.batch_alter_table('transaction_category_override', schema=None) as batch_op:
        batch_op.create_foreign_key('transaction_category_override_ibfk_1', 'transactions', ['transaction_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
