"""Add is_enabled to Account

Revision ID: 268d975c59d6
Revises: 90422c00678f
Create Date: 2024-02-13 22:45:48.693018

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy_utils import EncryptedType

# revision identifiers, used by Alembic.
revision = '268d975c59d6'
down_revision = '90422c00678f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_enabled', sa.Boolean(), nullable=False, server_default=sa.true()))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('token',
               existing_type=sa.VARCHAR(length=500),
               type_=EncryptedType(),
               existing_nullable=True)
        batch_op.drop_constraint('uq_user_token', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_token', ['token'])
        batch_op.alter_column('token',
               existing_type=sqlalchemy_utils.types.encrypted.encrypted_type.EncryptedType(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_column('is_enabled')

    # ### end Alembic commands ###
