"""Add requires_update to Credential

Revision ID: 52eeab73cc9f
Revises: 268d975c59d6
Create Date: 2024-02-14 22:11:27.860127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52eeab73cc9f'
down_revision = '268d975c59d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credential', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requires_update', sa.Boolean(), nullable=False, server_default=sa.text('FALSE')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credential', schema=None) as batch_op:
        batch_op.drop_column('requires_update')

    # ### end Alembic commands ###
