"""Initial migration to MySQL.

Revision ID: 59affccd63cd
Revises: 52eeab73cc9f
Create Date: 2024-03-14 22:51:54.322010

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '59affccd63cd'
down_revision = '52eeab73cc9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=7),
               type_=sa.String(length=20),
               nullable=False)
        batch_op.alter_column('credential_id',
               existing_type=mysql.TINYINT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('plaid_account_id',
               existing_type=mysql.VARCHAR(length=37),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=36),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('type',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('subtype',
               existing_type=mysql.VARCHAR(length=14),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('mask',
               existing_type=mysql.SMALLINT(),
               type_=sa.String(length=4),
               existing_nullable=True)
        batch_op.alter_column('is_enabled',
               existing_type=mysql.TINYINT(),
               nullable=False)
        batch_op.create_unique_constraint(None, ['plaid_account_id'])
        batch_op.create_foreign_key(None, 'credential', ['credential_id'], ['id'])

    with op.batch_alter_table('credential', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.TINYINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=7),
               type_=sa.String(length=10),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=mysql.TINYINT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('institution_name',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('access_token',
               existing_type=sa.VARBINARY(length=255),
               type_=sqlalchemy_utils.types.encrypted.encrypted_type.EncryptedType(),
               existing_nullable=True)
        batch_op.alter_column('requires_update',
               existing_type=mysql.TINYINT(),
               nullable=False)
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('plaid_transaction', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=mysql.TINYINT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('user_ip',
               existing_type=mysql.VARCHAR(length=9),
               type_=sa.String(length=45),
               nullable=False)
        batch_op.alter_column('credential_id',
               existing_type=mysql.TINYINT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('account_id',
               existing_type=mysql.VARCHAR(length=0),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('operation',
               existing_type=mysql.VARCHAR(length=44),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('posted_transactions',
               existing_type=mysql.VARCHAR(length=0),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('pending_transactions',
               existing_type=mysql.VARCHAR(length=0),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'account', ['account_id'], ['id'])
        batch_op.create_foreign_key(None, 'credential', ['credential_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.TINYINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=6),
               type_=sa.String(length=80),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=22),
               type_=sa.String(length=120),
               nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(length=162),
               type_=sa.String(length=256),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=6),
               type_=sa.String(length=20),
               nullable=False)
        batch_op.alter_column('role',
               existing_type=mysql.VARCHAR(length=4),
               type_=sa.String(length=20),
               nullable=False)
        batch_op.alter_column('token',
               existing_type=mysql.VARCHAR(length=172),
               type_=sqlalchemy_utils.types.encrypted.encrypted_type.EncryptedType(),
               existing_nullable=True)
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('token',
               existing_type=sqlalchemy_utils.types.encrypted.encrypted_type.EncryptedType(),
               type_=mysql.VARCHAR(length=172),
               existing_nullable=True)
        batch_op.alter_column('role',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=4),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=6),
               nullable=True)
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=256),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=120),
               type_=mysql.VARCHAR(length=22),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.String(length=80),
               type_=mysql.VARCHAR(length=6),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('plaid_transaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('pending_transactions',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=0),
               existing_nullable=True)
        batch_op.alter_column('posted_transactions',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=0),
               existing_nullable=True)
        batch_op.alter_column('operation',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=44),
               existing_nullable=True)
        batch_op.alter_column('account_id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=0),
               existing_nullable=True)
        batch_op.alter_column('credential_id',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(),
               existing_nullable=True)
        batch_op.alter_column('user_ip',
               existing_type=sa.String(length=45),
               type_=mysql.VARCHAR(length=9),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(),
               nullable=True)
        batch_op.alter_column('timestamp',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('credential', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('requires_update',
               existing_type=mysql.TINYINT(),
               nullable=True)
        batch_op.alter_column('access_token',
               existing_type=sqlalchemy_utils.types.encrypted.encrypted_type.EncryptedType(),
               type_=sa.VARBINARY(length=255),
               existing_nullable=True)
        batch_op.alter_column('institution_name',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(length=7),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('is_enabled',
               existing_type=mysql.TINYINT(),
               nullable=True)
        batch_op.alter_column('mask',
               existing_type=sa.String(length=4),
               type_=mysql.SMALLINT(),
               existing_nullable=True)
        batch_op.alter_column('subtype',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=14),
               existing_nullable=True)
        batch_op.alter_column('type',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=True)
        batch_op.alter_column('plaid_account_id',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=37),
               nullable=True)
        batch_op.alter_column('credential_id',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=7),
               nullable=True)

    # ### end Alembic commands ###
