"""empty message

Revision ID: 6a0537905d47
Revises: f8b40c927394
Create Date: 2025-10-16 21:38:10.025156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a0537905d47'
down_revision = 'f8b40c927394'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_transactions_user_custom_category')
        batch_op.create_foreign_key(None, 'credential', ['credential_id'], ['id'])
        batch_op.create_foreign_key(None, 'account', ['account_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index('ix_transactions_user_custom_category', ['user_id', 'custom_category_id'], unique=False)

    # ### end Alembic commands ###
