"""empty message

Revision ID: 829f0fd09626
Revises: cb59cf25039a
Create Date: 2025-10-19 14:48:27.463774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '829f0fd09626'
down_revision = 'cb59cf25039a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('custom_categories', schema=None) as batch_op:
        batch_op.drop_constraint('custom_categories_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('transaction_category_override', schema=None) as batch_op:
        batch_op.drop_constraint('fk_override_custom_category', type_='foreignkey')
        batch_op.create_foreign_key(None, 'custom_categories', ['custom_category_id'], ['id'])

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_transactions_custom_category', type_='foreignkey')
        batch_op.create_foreign_key(None, 'custom_categories', ['custom_category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_transactions_custom_category', 'custom_categories', ['custom_category_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('transaction_category_override', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_override_custom_category', 'custom_categories', ['custom_category_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('custom_categories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('custom_categories_ibfk_1', 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
