"""Add status and role to User, add status to Account

Revision ID: 90422c00678f
Revises: e4f2ce0507fc
Create Date: 2024-01-27 11:30:19.987159

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = '90422c00678f'
down_revision = 'e4f2ce0507fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add 'status' column to 'account', initially allowing NULL
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20)))

    # Add 'status' and 'role' columns to 'user', initially allowing NULL
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20)))
        batch_op.add_column(sa.Column('role', sa.String(length=20)))

    # Set default values for the new columns
    op.execute('UPDATE account SET status = "Active" WHERE status IS NULL')
    op.execute('UPDATE user SET status = "Active", role = "user" WHERE status IS NULL OR role IS NULL')

    # Alter 'status' and 'role' columns to be NOT NULL
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.alter_column('status', nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('status', nullable=False)
        batch_op.alter_column('role', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')
        batch_op.drop_column('status')

    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
