"""Initial migration.

Revision ID: 972b0e8b1cb3
Revises: 
Create Date: 2023-11-27 22:03:32.287987

"""
from alembic import op
import sqlalchemy as sa
from config import Config
import sqlalchemy_utils  # Add this line


# revision identifiers, used by Alembic.
revision = '972b0e8b1cb3'
down_revision = None
branch_labels = None
depends_on = None

key = Config.ENCRYPTION_KEY

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credential',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('institution_name', sa.String(length=100), nullable=True),
    sa.Column('access_token', sqlalchemy_utils.EncryptedType(sa.String(), key), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credential_id', sa.Integer(), nullable=False),
    sa.Column('plaid_account_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('subtype', sa.String(length=50), nullable=True),
    sa.Column('mask', sa.String(length=4), nullable=True),
    sa.ForeignKeyConstraint(['credential_id'], ['credential.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plaid_account_id')
    )
    op.create_table('plaid_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('user_ip', sa.String(length=45), nullable=False),
    sa.Column('credential_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('operation', sa.String(length=100), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['credential_id'], ['credential.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plaid_transaction')
    op.drop_table('account')
    op.drop_table('credential')
    # ### end Alembic commands ###
