"""empty message

Revision ID: cb59cf25039a
Revises: b671a97a0ad1
Create Date: 2025-10-19 14:09:11.053916

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cb59cf25039a'
down_revision = 'b671a97a0ad1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    inspector = sa.inspect(op.get_bind())

    rule_columns = {col['name'] for col in inspector.get_columns('category_rules')}
    if {'label', 'color'} <= rule_columns:
        with op.batch_alter_table('category_rules', schema=None) as batch_op:
            batch_op.drop_column('label')
            batch_op.drop_column('color')

    custom_indexes = {index['name'] for index in inspector.get_indexes('custom_categories')}
    custom_fks = {fk['name'] for fk in inspector.get_foreign_keys('custom_categories') if fk.get('name')}
    with op.batch_alter_table('custom_categories', schema=None) as batch_op:
        if 'custom_categories_ibfk_1' in custom_fks:
            batch_op.drop_constraint('custom_categories_ibfk_1', type_='foreignkey')
            batch_op.create_foreign_key('custom_categories_ibfk_1', 'user', ['user_id'], ['id'], ondelete='CASCADE')
        elif not custom_fks:
            batch_op.create_foreign_key('custom_categories_ibfk_1', 'user', ['user_id'], ['id'], ondelete='CASCADE')
        if 'uq_custom_categories_user_name' not in custom_indexes:
            batch_op.create_index('uq_custom_categories_user_name', ['user_id', 'name'], unique=True)

    override_columns = {col['name'] for col in inspector.get_columns('transaction_category_override')}
    override_fks = {fk['name'] for fk in inspector.get_foreign_keys('transaction_category_override') if fk.get('name')}
    with op.batch_alter_table('transaction_category_override', schema=None) as batch_op:
        if 'fk_override_custom_category' in override_fks:
            batch_op.drop_constraint('fk_override_custom_category', type_='foreignkey')
        batch_op.create_foreign_key('fk_override_custom_category', 'custom_categories', ['custom_category_id'], ['id'], ondelete='SET NULL')
        if 'label' in override_columns:
            batch_op.drop_column('label')
        if 'color' in override_columns:
            batch_op.drop_column('color')

    transaction_fks = {fk['name'] for fk in inspector.get_foreign_keys('transactions') if fk.get('name')}
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        if 'fk_transactions_custom_category' in transaction_fks:
            batch_op.drop_constraint('fk_transactions_custom_category', type_='foreignkey')
        batch_op.create_foreign_key('fk_transactions_custom_category', 'custom_categories', ['custom_category_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    inspector = sa.inspect(op.get_bind())

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        if any(fk.get('name') == 'fk_transactions_custom_category' for fk in inspector.get_foreign_keys('transactions')):
            batch_op.drop_constraint('fk_transactions_custom_category', type_='foreignkey')
        batch_op.create_foreign_key('fk_transactions_custom_category', 'custom_categories', ['custom_category_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('transaction_category_override', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', mysql.VARCHAR(length=7), nullable=True))
        batch_op.add_column(sa.Column('label', mysql.VARCHAR(length=255), nullable=False))
        if any(fk.get('name') == 'fk_override_custom_category' for fk in inspector.get_foreign_keys('transaction_category_override')):
            batch_op.drop_constraint('fk_override_custom_category', type_='foreignkey')
        batch_op.create_foreign_key('fk_override_custom_category', 'custom_categories', ['custom_category_id'], ['id'], ondelete='SET NULL')

    custom_indexes = {index['name'] for index in inspector.get_indexes('custom_categories')}
    custom_fks = {fk['name'] for fk in inspector.get_foreign_keys('custom_categories') if fk.get('name')}
    with op.batch_alter_table('custom_categories', schema=None) as batch_op:
        if 'custom_categories_ibfk_1' in custom_fks:
            batch_op.drop_constraint('custom_categories_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key('custom_categories_ibfk_1', 'user', ['user_id'], ['id'], ondelete='CASCADE')
        if 'uq_custom_categories_user_name' not in custom_indexes:
            batch_op.create_index('uq_custom_categories_user_name', ['user_id', 'name'], unique=True)

    with op.batch_alter_table('category_rules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', mysql.VARCHAR(length=7), server_default=sa.text("'#2C6B4F'"), nullable=False))
        batch_op.add_column(sa.Column('label', mysql.VARCHAR(length=255), nullable=False))
    
    # ### end Alembic commands ###
