"""Added API token generator

Revision ID: e4f2ce0507fc
Revises: 445cff948dcb
Create Date: 2023-12-09 17:17:30.028131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4f2ce0507fc'
down_revision = '445cff948dcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token', sa.String(length=500), nullable=True))
        batch_op.create_unique_constraint('uq_user_token', ['token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_token', type_='unique')
        batch_op.drop_column('token')

    # ### end Alembic commands ###
