"""Initial migration

Revision ID: f8b40c927394
Revises: 
Create Date: 2025-10-16 19:44:27.599733

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f8b40c927394'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = set(inspector.get_table_names())

    if 'plaid_transaction' in existing_tables:
        op.drop_table('plaid_transaction')

    if 'subscription' in existing_tables:
        op.drop_table('subscription')

    if 'budgets' in existing_tables:
        fk_names = {fk['name'] for fk in inspector.get_foreign_keys('budgets')}
        index_names = {idx['name'] for idx in inspector.get_indexes('budgets')}
        with op.batch_alter_table('budgets', schema=None) as batch_op:
            if 'fk_budgets_user_id' in fk_names:
                batch_op.drop_constraint('fk_budgets_user_id', type_='foreignkey')
            if 'ix_budgets_user_id' in index_names:
                batch_op.drop_index('ix_budgets_user_id')
            batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    if 'categories' in existing_tables:
        fk_names = {fk['name'] for fk in inspector.get_foreign_keys('categories')}
        index_names = {idx['name'] for idx in inspector.get_indexes('categories')}
        with op.batch_alter_table('categories', schema=None) as batch_op:
            if 'fk_categories_user_id' in fk_names:
                batch_op.drop_constraint('fk_categories_user_id', type_='foreignkey')
            if 'ix_categories_user_label' in index_names:
                batch_op.drop_index('ix_categories_user_label')
            if 'ix_categories_user_created' in index_names:
                batch_op.drop_index('ix_categories_user_created')
            batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    if 'credential' in existing_tables:
        columns = {col['name'] for col in inspector.get_columns('credential')}
        with op.batch_alter_table('credential', schema=None) as batch_op:
            if 'next_cursor' in columns:
                batch_op.drop_column('next_cursor')

    if 'transaction_category_override' in existing_tables:
        fk_names = {fk['name'] for fk in inspector.get_foreign_keys('transaction_category_override')}
        with op.batch_alter_table('transaction_category_override', schema=None) as batch_op:
            if 'fk_transaction_override_transaction' in fk_names:
                batch_op.drop_constraint('fk_transaction_override_transaction', type_='foreignkey')
            batch_op.create_foreign_key(None, 'transactions', ['transaction_id'], ['id'])

    if 'transactions' in existing_tables:
        fk_metadata = inspector.get_foreign_keys('transactions')
        index_names = {idx['name'] for idx in inspector.get_indexes('transactions')}
        columns = {col['name'] for col in inspector.get_columns('transactions')}
        with op.batch_alter_table('transactions', schema=None) as batch_op:
            for fk in fk_metadata:
                fk_name = fk.get('name')
                if fk_name:
                    batch_op.drop_constraint(fk_name, type_='foreignkey')
            if 'ix_transactions_user_id' in index_names:
                batch_op.drop_index('ix_transactions_user_id')
            if 'ix_transactions_user_date_id' in index_names:
                batch_op.drop_index('ix_transactions_user_date_id')
            if 'ix_transactions_parent_transaction_id' in index_names:
                batch_op.drop_index('ix_transactions_parent_transaction_id')
            if 'ix_transactions_account_id' in index_names:
                batch_op.drop_index('ix_transactions_account_id')
            batch_op.create_foreign_key(None, 'transactions', ['parent_transaction_id'], ['id'])
            batch_op.create_foreign_key(None, 'categories', ['custom_category_id'], ['id'])
            if 'custom_category_label' in columns:
                batch_op.drop_column('custom_category_label')
            if 'custom_category_source' in columns:
                batch_op.drop_column('custom_category_source')
            if 'custom_category_color' in columns:
                batch_op.drop_column('custom_category_color')

    if 'user' in existing_tables:
        columns = {col['name'] for col in inspector.get_columns('user')}
        with op.batch_alter_table('user', schema=None) as batch_op:
            if 'token' in columns:
                batch_op.drop_column('token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token', sa.BLOB(), nullable=True))

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_category_color', mysql.VARCHAR(length=7), nullable=True))
        batch_op.add_column(sa.Column('custom_category_source', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('custom_category_label', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_transactions_parent_transaction', 'transactions', ['parent_transaction_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_transactions_custom_category_id', 'categories', ['custom_category_id'], ['id'], ondelete='SET NULL')
        batch_op.create_index('ix_transactions_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_transactions_user_date_id', ['user_id', 'date', 'id'], unique=False)
        batch_op.create_index('ix_transactions_user_custom_category', ['user_id', 'custom_category_id'], unique=False)
        batch_op.create_index('ix_transactions_parent_transaction_id', ['parent_transaction_id'], unique=False)
        batch_op.create_index('ix_transactions_account_id', ['account_id'], unique=False)

    with op.batch_alter_table('transaction_category_override', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_transaction_override_transaction', 'transactions', ['transaction_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('credential', schema=None) as batch_op:
        batch_op.add_column(sa.Column('next_cursor', sa.BLOB(), nullable=True))

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_categories_user_id', 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index('ix_categories_user_label', ['user_id', 'label'], unique=False)
        batch_op.create_index('ix_categories_user_created', ['user_id', 'created_at'], unique=False)

    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_budgets_user_id', 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index('ix_budgets_user_id', ['user_id'], unique=False)

    op.create_table('subscription',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tier_limit', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('price_cents', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('billing_interval', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('start_date', mysql.DATETIME(), nullable=False),
    sa.Column('renewal_date', mysql.DATETIME(), nullable=False),
    sa.Column('cancellation_date', mysql.DATETIME(), nullable=True),
    sa.Column('waived_periods', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('stripe_subscription_id', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('stripe_customer_id', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('tos_accepted_at', mysql.DATETIME(), nullable=True),
    sa.Column('is_vip', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='subscription_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('plaid_transaction',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('posted_transactions', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pending_transactions', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('timestamp', mysql.DATETIME(), nullable=False),
    sa.Column('user_ip', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('credential_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('account_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('operation', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('response', mysql.TEXT(), nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], name='plaid_transaction_ibfk_2'),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], name='plaid_transaction_ibfk_5'),
    sa.ForeignKeyConstraint(['credential_id'], ['credential.id'], name='plaid_transaction_ibfk_3'),
    sa.ForeignKeyConstraint(['credential_id'], ['credential.id'], name='plaid_transaction_ibfk_6'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='plaid_transaction_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='plaid_transaction_ibfk_4'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
